export enum CurrencyCode {
	USD = 'USD',
	EUR = 'EUR',
	AUD = 'AUD',
	BRL = 'BRL',
	CAD = 'CAD',
	CHF = 'CHF',
	CNY = 'CNY',
	GBP = 'GBP',
	HKD = 'HKD',
	INR = 'INR',
	JPY = 'JPY',
	KRW = 'KRW',
	MXN = 'MXN',
	NOK = 'NOK',
	RUB = 'RUB',
	SEK = 'SEK',
}
